# dataset cfgs
dataset:
  common:
    NAME: HumanDataset
    data_dir: './data/human'
  train:
    split: train
  val:
    split: val
    num_points: 2048

num_points: 2048  # the number of points passed into model
num_classes: &nclass
  2

datatransforms:
  train: [PointsToTensor, PointCloudScaling, PointCloudCenterAndNormalize, PointCloudRotation]
  vote: [PointCloudRotation]
  val: [PointsToTensor, PointCloudCenterAndNormalize]
  kwargs:
    scale: [0.9, 1.1]
    angle: [0.0, 1.0, 0.0]
    gravity_dim: 1

batch_size: 16
val_batch_size: 4
dataloader:
  num_workers: 6


# training cfgs
criterion_args:
  NAME: SmoothCrossEntropy
  label_smoothing: 0.3

lr: 0.002
optimizer:
 NAME: 'adamw'
 weight_decay: 0.05

sched: cosine
sched_on_epoch: True
step_per_update: 1
epochs: 250
start_epoch: 1
warmup_epochs: 0
min_lr: 1.0e-4
t_max: 200

grad_norm_clip: 10


# io and misc
log_dir: 'human_dataset'
root_dir: log/
print_freq: 10
val_freq: 1
save_freq: -1

mode: 'train' # set to test for inference only
seed: null
pretrained_path: null 

wandb:
  project: point_osr
  use_wandb: True

launcher: 'mp'
local_rank: 0
deterministic: False