batch_size: 16
criterion_args:
  NAME: SmoothCrossEntropy
  label_smoothing: 0.3
dataloader:
  num_workers: 6
dataset:
  common:
    NAME: HumanDataset
    data_dir: /home/cerlab/Documents/data/pointosr/eval_human
  test:
    split: test
  train:
    split: train
  val:
    num_points: 2048
    split: val
datatransforms:
  kwargs:
    angle:
    - 0.0
    - 1.0
    - 0.0
    gravity_dim: 1
    scale:
    - 0.9
    - 1.1
  train:
  - PointsToTensor
  - PointCloudScaling
  - PointCloudCenterAndNormalize
  - PointCloudRotation
  val:
  - PointsToTensor
  - PointCloudCenterAndNormalize
  vote:
  - PointCloudRotation
deterministic: false
epochs: 250
grad_norm_clip: 10
launcher: mp
local_rank: 0
log_dir: human_dataset
lr: 0.002
min_lr: 0.0001
mode: train
num_classes: 2
num_points: 2048
optimizer:
  NAME: adamw
  weight_decay: 0.05
pretrained_path: null
print_freq: 10
root_dir: log/
save_freq: -1
sched: cosine
sched_on_epoch: true
seed: null
start_epoch: 1
step_per_update: 1
t_max: 200
val_batch_size: 3
val_freq: 1
wandb:
  project: inference_test
  use_wandb: false
warmup_epochs: 0
