# dataset cfgs
dataset:
  common:
    NAME: HumanDataset
    data_dir: '/home/cerlab/Documents/data/pointosr/human'
  train:
    split: train
  val:
    split: val
    num_points: 2048
  test:
    split: test
  calibration:
    split: calib
    num_points: 2048
  # Evaluation dataset (separate from training)
  eval:
    NAME: HumanDataset
    data_dir: '/home/cerlab/Documents/data/pointosr/eval_human'
    split: test
    num_points: 2048

num_points: 2048  # the number of points passed into model
num_classes: &nclass
  2

datatransforms:
  train: [PointsToTensor, PointCloudScaling, PointCloudCenterAndNormalize, PointCloudRotation]
  vote: [PointCloudRotation]
  val: [PointsToTensor, PointCloudCenterAndNormalize]
  test: [PointsToTensor, PointCloudCenterAndNormalize]
  calibration: [PointsToTensor, PointCloudCenterAndNormalize]
  kwargs:
    scale: [0.95, 1.05]
    angle: [0.0, 1.0, 0.0]
    gravity_dim: 1

batch_size: 32
val_batch_size: 32
dataloader:
  num_workers: 6

# training cfgs
criterion_args:
  NAME: SmoothCrossEntropy
  label_smoothing: 0.3

lr: 0.002
optimizer:
 NAME: 'adamw'
 weight_decay: 0.05

sched: cosine
sched_on_epoch: True
step_per_update: 1
epochs: 250
start_epoch: 1
warmup_epochs: 0
min_lr: 1.0e-4
t_max: 200

grad_norm_clip: 10

# io and misc
mode: 'train' # set to test for inference only, 'osr_eval' for OSR evaluation
pretrained_path: null
seed: 42

# OSR evaluation settings
osr_eval:
  eval_dataset: 'eval'  # Use the eval dataset configuration
  fusion_config_path: '/home/cerlab/Documents/pointosr_ws/src/pointosr/pointosr/osr/calibration/fusion_config.json'
  stats_path: '/home/cerlab/Documents/pointosr_ws/src/pointosr/pointosr/osr/calibration/stats.json'
  prototypes_path: '/home/cerlab/Documents/pointosr_ws/src/pointosr/pointosr/osr/prototypes'
  results_dir: '/home/cerlab/Documents/pointosr_ws/src/pointosr/pointosr/osr/evaluation'

wandb:
  project: pointosr
  use_wandb: True

log_dir: 'osr_human_dataset'  # Updated log directory name
root_dir: log/
print_freq: 10
val_freq: 1
save_freq: -1

launcher: 'mp'
local_rank: 0
deterministic: True

# osr (open set recognition) default settings
osr:
  target_tpr: 0.99              # Target True Positive Rate for ID samples
  K_H: 6                        # Number of human prototypes  
  K_F: 4                        # Number of false-positive prototypes
  fused_weights: [0.5, 0.5]     # Initial weights for [energy, cosine] fusion
  temperature_init: 1.0         # Initial temperature for calibration
  
  calibration_dir: '/home/cerlab/Documents/data/pointosr/human'
  splits_dir: '/home/cerlab/Documents/data/pointosr/dataset/splits'
  
  output_dirs:
    prototypes: 'osr/prototypes'
    calibration: 'osr/calibration' 
    metrics: 'osr/metrics'
    exports: 'model/exports'
    checkpoints: 'model/checkpoints'


checkpoint:
  save_path: 'model/checkpoints/osr_best.pth'  # OSR-specific checkpoint name
  save_freq: 10  # Save checkpoint every 10 epochs
  keep_interval: 50  # Keep checkpoints every 50 epochs
