# OSR-specific configuration extending default settings
# This config uses the new OSR splits created in /home/cerlab/Documents/data/pointosr/human/

# dataset cfgs - Updated to use new OSR splits
dataset:
  common:
    NAME: HumanDataset
    data_dir: '/home/cerlab/Documents/data/pointosr/human'  # Updated path to our OSR splits
  train:
    split: train
  val:
    split: val
    num_points: 2048
  test:
    split: test
  calibration:  # New split for OSR calibration
    split: cal
    num_points: 2048

num_points: 2048  # the number of points passed into model
num_classes: &nclass
  2

# Updated data transforms - refined for OSR (slightly less aggressive augmentation)
datatransforms:
  train: [PointsToTensor, PointCloudScaling, PointCloudCenterAndNormalize, PointCloudRotation]
  vote: [PointCloudRotation]
  val: [PointsToTensor, PointCloudCenterAndNormalize]
  test: [PointsToTensor, PointCloudCenterAndNormalize]  # No augmentation for test
  calibration: [PointsToTensor, PointCloudCenterAndNormalize]  # No augmentation for calibration
  kwargs:
    scale: [0.95, 1.05]  # Slightly less aggressive scaling for OSR
    angle: [0.0, 1.0, 0.0]  # Yaw rotation only
    gravity_dim: 1

batch_size: 16
val_batch_size: 4
dataloader:
  num_workers: 6

# training cfgs
criterion_args:
  NAME: SmoothCrossEntropy
  label_smoothing: 0.3

lr: 0.002
optimizer:
 NAME: 'adamw'
 weight_decay: 0.05

sched: cosine
sched_on_epoch: True
step_per_update: 1
epochs: 250
start_epoch: 1
warmup_epochs: 0
min_lr: 1.0e-4
t_max: 200

grad_norm_clip: 10

# io and misc
mode: 'train' # set to test for inference only
pretrained_path: null
seed: 42  # Fixed seed for reproducibility

wandb:
  project: point_osr
  use_wandb: False

log_dir: 'osr_human_dataset'  # Updated log directory name
root_dir: log/
print_freq: 10
val_freq: 1
save_freq: -1

launcher: 'mp'
local_rank: 0
deterministic: True  # Enable deterministic training for OSR

# OSR-specific settings
osr:
  target_tpr: 0.99              # Target True Positive Rate for ID samples
  K_H: 6                        # Number of human prototypes  
  K_F: 4                        # Number of false-positive prototypes
  fused_weights: [0.5, 0.5]     # Initial weights for [energy, cosine] fusion
  temperature_init: 1.0         # Initial temperature for calibration
  
  # Paths for OSR artifacts (relative to project root)
  calibration_dir: '/home/cerlab/Documents/data/pointosr/human'
  calibration_metadata: '/home/cerlab/Documents/data/pointosr/human/calibration_selection.json'
  
  # Directory structure for OSR outputs
  output_dirs:
    prototypes: 'osr/prototypes'
    calibration: 'osr/calibration' 
    metrics: 'osr/metrics'
    exports: 'model/exports'
    checkpoints: 'model/checkpoints'

# Model checkpoint settings - save to dedicated location for OSR
checkpoint:
  save_path: 'model/checkpoints/osr_best.pth'  # OSR-specific checkpoint name
  save_freq: 10  # Save checkpoint every 10 epochs
  keep_interval: 50  # Keep checkpoints every 50 epochs
